# 应用名称
spring.application.name: eureka-server
# 如果不用ip的方式,可以使用主机名的方式
eureka.instance.hostname: eurekaserver1
#应用端口号
server.port: 1111
#关闭注册中心自我保护功能，防止关闭实例无法被剔除
eureka.server.enable-self-preservation: false

# 由于是注册中心，设置不向注册中心注册自己
eureka.client.register-with-eureka: false
# 由于注册中心职责是维护服务实例，不需要检索服务
eureka.client.fetch-registry: false
# 注册中心地址
eureka.client.serviceUrl.defaultZone: http://eurekaserver1:1111/eureka/